export const queryKeys = {
  config: ["config"] as const,
  health: ["health"] as const,
  models: ["models"] as const,
  projects: ["projects"] as const,
  project: (projectId: string) => ["project", projectId] as const,
  story: (projectId: string) => ["story", projectId] as const,
  storyReferences: (projectId: string, sceneId?: string | null) => ["story-references", projectId, sceneId ?? null] as const,
  storySuggestions: (projectId: string, query: string) => ["story-suggestions", projectId, query] as const,
  characters: (projectId: string) => ["characters", projectId] as const,
  character: (projectId: string, characterId?: string | null) => ["character", projectId, characterId ?? null] as const,
  assets: (projectId: string) => ["assets", projectId] as const,
  asset: (projectId: string, assetId?: string | null) => ["asset", projectId, assetId ?? null] as const,
  warnings: (projectId: string) => ["warnings", projectId] as const,
  versions: (projectId: string) => ["versions", projectId] as const,
  versionBranches: (projectId: string) => ["version-branches", projectId] as const,
  versionCompare: (projectId: string, leftId?: string | null, rightId?: string | null) => ["version-compare", projectId, leftId ?? null, rightId ?? null] as const,
  exports: (projectId: string) => ["exports", projectId] as const,
  export: (projectId: string, exportId?: string | null) => ["export", projectId, exportId ?? null] as const,
  generationJobs: (projectId: string) => ["generation-jobs", projectId] as const,
  generationJob: (projectId: string, jobId?: string | null) => ["generation-job", projectId, jobId ?? null] as const,
  generationBoards: (projectId: string) => ["generation-boards", projectId] as const,
  generationStory: (projectId: string) => ["generation-story", projectId] as const,
  generationVersions: (projectId: string) => ["generation-versions", projectId] as const,
  generationModels: ["generation-models"] as const,
};
